### ISSUE TITLE
Update versionCode

### ISSUE THREAD

**Issue by krt16s** [scoute-dich/Baumann_Theme#3]
You released multiple versions, but all having the same versionCode 12. For Android this means, all versions are the same. The VC is an integer that gets checked if its a newer version.. the versionName is just a fancy public facing string. Please see https://developer.android.com/tools/publishing/versioning.html for details.

**Comment by scoute-dich** [comment]
Thanks a lot. I just wondered why Fdroid didn't recognize the updates. I'm new on publishing apps, so I just didn't know that I must change version code. Will change it later.
