### ISSUE TITLE
bootup android version

### ISSUE THREAD

**Issue by huggla** [scoute-dich/Baumann_Theme#5]
Bootup says Android Marshmallow when running Lollipop

**Comment by beli3ver** [comment]
Because, that is an image not an text.

**Comment by huggla** [comment]
Remove the text from the image then.

**Comment by beli3ver** [comment]
I am not the developer, but maybe it would be nice if you could **ask **and not **order **i

**Comment by huggla** [comment]
Sorry, didnt mean to sound rude im just not that good on typing on my phone. I tend to keep my comments short.

**Comment by scoute-dich** [comment]
Hi,

`Remove the text from the image then.` - I made this theme mainly for my purposes and I'm running CM13 on my four year old Note 1. So I made the bootscreen showing a marshmallow logo. I can only include one bootanimation. So my suggestions:

- You can use my theme without the "marshmallow bootanimation" in combination with the bootanimation from an other theme (for example the system default)
- fork my theme and change the bootanimation in the assets folder

In the meantime: thanks for using my theme. It's a pleasure to see that a few people are using it.

Regards
scoute-dich

**Comment by huggla** [comment]
OK, thats fine with me but you really should tell fdroid to mention marshmallow and not only lollypop in the package info.

**Comment by beli3ver** [comment]
No the package work for both versions. That is important, not the reaseon that there is a text with other versions.
