### ISSUE TITLE
New icon requests

### ISSUE THREAD

**Issue by witchent** [scoute-dich/Baumann_Theme#6]
Hey there,
If you get the time for those I would really appreciate it. They are all from fdroid:

<item component="ComponentInfo{org.sufficientlysecure.viewer/org.ebookdroid.ui.library.RecentActivity}" drawable="org_sufficientlysecure_viewer_org_ebookdroid_ui_library_RecentActivity"/>

<item component="ComponentInfo{com.holokenmod/com.holokenmod.MainActivity}" drawable="com_holokenmod_com_holokenmod_MainActivity"/>

<item component="ComponentInfo{org.kde.kdeconnect_tp/org.kde.kdeconnect.UserInterface.MaterialActivity}" drawable="org_kde_kdeconnect_tp_org_kde_kdeconnect_UserInterface_MaterialActivity"/>

<item component="ComponentInfo{org.totschnig.myexpenses/org.totschnig.myexpenses.activity.MyExpenses}" drawable="org_totschnig_myexpenses_org_totschnig_myexpenses_activity_MyExpenses"/>

<item component="ComponentInfo{org.quantumbadger.redreader/org.quantumbadger.redreader.activities.MainActivity}" drawable="org_quantumbadger_redreader_org_quantumbadger_redreader_activities_MainActivity"/>

**Comment by witchent** [comment]
"
<item component="ComponentInfo{org.sufficientlysecure.viewer/org.ebookdroid.ui.library.RecentActivity}" drawable="org_sufficientlysecure_viewer_org_ebookdroid_ui_library_RecentActivity"/>

<item component="ComponentInfo{com.holokenmod/com.holokenmod.MainActivity}" drawable="com_holokenmod_com_holokenmod_MainActivity"/>

<item component="ComponentInfo{org.kde.kdeconnect_tp/org.kde.kdeconnect.UserInterface.MaterialActivity}" drawable="org_kde_kdeconnect_tp_org_kde_kdeconnect_UserInterface_MaterialActivity"/>

<item component="ComponentInfo{org.totschnig.myexpenses/org.totschnig.myexpenses.activity.MyExpenses}" drawable="org_totschnig_myexpenses_org_totschnig_myexpenses_activity_MyExpenses"/>

<item component="ComponentInfo{org.quantumbadger.redreader/org.quantumbadger.redreader.activities.MainActivity}" drawable="org_quantumbadger_redreader_org_quantumbadger_redreader_activities_MainActivity"/>
"

**Comment by witchent** [comment]
Sry, somehow formatting doesn't work on mobile. I try it one more time:
```
<!-- Document Viewer -->
<item component="ComponentInfo{org.sufficientlysecure.viewer/org.ebookdroid.ui.library.RecentActivity}" drawable="org_sufficientlysecure_viewer_org_ebookdroid_ui_library_RecentActivity"/>
<!-- HoloKenMod -->
<item component="ComponentInfo{com.holokenmod/com.holokenmod.MainActivity}" drawable="com_holokenmod_com_holokenmod_MainActivity"/>
<!-- KDE Connect -->
<item component="ComponentInfo{org.kde.kdeconnect_tp/org.kde.kdeconnect.UserInterface.MaterialActivity}" drawable="org_kde_kdeconnect_tp_org_kde_kdeconnect_UserInterface_MaterialActivity"/>
<!-- My Expenses -->
<item component="ComponentInfo{org.totschnig.myexpenses/org.totschnig.myexpenses.activity.MyExpenses}" drawable="org_totschnig_myexpenses_org_totschnig_myexpenses_activity_MyExpenses"/>
<!-- RedReader Beta -->
<item component="ComponentInfo{org.quantumbadger.redreader/org.quantumbadger.redreader.activities.MainActivity}" drawable="org_quantumbadger_redreader_org_quantumbadger_redreader_activities_MainActivity"/>
```

**Comment by scoute-dich** [comment]
Hi,

I added your icons. Will be there in the next release.

**Comment by witchent** [comment]
Awesome, thanks :)
